<?php

/**
 * AuthorInheritanceConcrete
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: AuthorInheritanceConcrete.class.php 15966 2015-04-08 08:45:44Z wimulkeman $
 */
class AuthorInheritanceConcrete extends BaseAuthorInheritanceConcrete
{

}