<?php

/**
 * FormGeneratorTest3
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: FormGeneratorTest3.class.php 15966 2015-04-08 08:45:44Z wimulkeman $
 */
class FormGeneratorTest3 extends BaseFormGeneratorTest3
{
}
